coverage:
  range: 50..75
  round: down
  precision: 2
  status:
    project:
      default:
        threshold: "5%"
    changes: false
    patch:
      default:
        target: 80
  ignore:
    - "**/migrations"
