version: '3.9'
services:
  db:
    volumes:
      - ./volumes/database:/opt/postgres/data
      - ./volumes/backups:/backups
    ports:
      - "${DATABASE_PORT:-7432}:5432"

  dbbackups:
    volumes:
      - ./volumes/backups:/backups

  worker:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_worker_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: worker
    volumes:
      - ../:/home/web/project
      - ../django_project:/home/web/django_project
      - ./volumes/media:/home/web/media
    links:
      - s3

  celery_beat:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_worker_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: worker
    volumes:
      - ../:/home/web/project
      - ../django_project:/home/web/django_project

  dev:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: vscode
    entrypoint: []
    volumes:
      - ../:/home/web/project
      - ./volumes/media:/home/web/media
      - ./volumes/static:/home/web/static
    links:
      - db
      - worker

  s3:
    image: quay.io/minio/minio:RELEASE.2024-03-30T09-41-56Z.fips
    command: minio server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID:-minios3admin}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY:-minios3admin}
    volumes:
      - ./volumes/s3_data:/data
    restart: always

  createbuckets:
    image: minio/mc
    depends_on:
      - s3
    environment:
      MINIO_S3_USER: ${AWS_ACCESS_KEY_ID:-minios3admin}
      MINIO_S3_PASSWORD: ${AWS_SECRET_ACCESS_KEY:-minios3admin}
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set s3minio http://s3:9000 $${MINIO_S3_USER} $${MINIO_S3_PASSWORD};
      /usr/bin/mc mb --ignore-existing s3minio/cplus;
      exit 0;
      "
