version: '3.9'
services:
  db:
    volumes:
      - ./volumes/database:/opt/postgres/data
      - ./volumes/backups:/backups
    ports:
      - "${DB_PORT:-7432}:5432"

  dbbackups:
    volumes:
      - ./volumes/backups:/backups

  django:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: prod
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media

  celery_beat:
    volumes:
      - ../django_project:/home/web/django_project

  worker:
    volumes:
      - ../django_project:/home/web/django_project

  dev:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: dev
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media

  nginx:
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/conf.d:ro
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
    ports:
      - "${HTTP_PORT:-8888}:80"
    links:
      - django
