version: '3.9'
services:
  db:
    volumes:
      - ./volumes/database:/opt/postgres/data
      - ./volumes/backups:/backups
    ports:
      - "${DB_PORT:-7432}:5432"

  dbbackups:
    volumes:
      - ./volumes/backups:/backups

  django:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: prod
    volumes:
      - ../django_project:/home/web/django_project

  celery_beat:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_worker_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: worker
    volumes:
      - ../:/home/web/project
      - ../django_project:/home/web/django_project

  worker:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_worker_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: worker
    volumes:
      - ../:/home/web/project
      - ../django_project:/home/web/django_project
    links:
      - gcs

  dev:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: dev
    entrypoint: []
    environment:
      - STORAGE_EMULATOR_HOST=http://gcs:4443
    volumes:
      - ../django_project:/home/web/django_project

  nginx:
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/conf.d:ro
    ports:
      - "${HTTP_PORT:-8888}:80"
    links:
      - django

  gcs:
    container_name: googlecloudstorage
    image: fsouza/fake-gcs-server:1.47.8
    command:
    - '-scheme'
    - 'http'
    - '-port'
    - '4443'
    - '-public-host'
    - '127.0.0.1:4443'
    - '-external-url'
    - 'http://127.0.0.1:4443'
    volumes:
      - ./volumes/gcs_data:/storage
      - ./gcs_emulator:/data
    ports:
      - 4443:4443
