version: '3.9'
services:
  db:
    volumes:
      - ./volumes/database:/opt/postgres/data
      - ./volumes/backups:/backups
    ports:
      - "${DATABASE_PORT:-7432}:5432"

  worker:
    image: kartoza/cplus-api:test
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/media:/home/web/media
    links:
      - db
      - redis

  dev:
    image: kartoza/cplus-api:test
    entrypoint: []
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
    links:
      - db
      - worker
  