version: '3.9'
services:
  db:
    volumes:
      - ./volumes/database:/opt/postgres/data
      - ./volumes/backups:/backups
    ports:
      - "${DB_PORT:-7432}:5432"

  dbbackups:
    volumes:
      - ./volumes/backups:/backups

  django:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: prod
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static

  celery_beat:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_worker_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: worker
    volumes:
      - ../:/home/web/project
      - ../django_project:/home/web/django_project

  worker:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_worker_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: worker
    volumes:
      - ../:/home/web/project
      - ../django_project:/home/web/django_project
      - ./volumes/media:/home/web/media

  dev:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: dev
    entrypoint: []
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
    links:
      - worker

  nginx:
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/conf.d:ro
      - ./volumes/static:/home/web/static
    ports:
      - "${HTTP_PORT:-8888}:80"

  minio:
    volumes:
      - ./volumes/minio_data:/data

  s3:
    image: quay.io/minio/minio:RELEASE.2024-03-30T09-41-56Z.fips
    command: minio server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${S3_AWS_ACCESS_KEY_ID:-minios3admin}
      MINIO_ROOT_PASSWORD: ${S3_AWS_SECRET_ACCESS_KEY:-minios3admin}
    volumes:
      - ./volumes/s3_data:/data
    restart: always
