# Generated by Django 4.2.7 on 2024-04-05 17:23

import cplus_api.models.layer
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cplus_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('created_on', models.DateTimeField()),
                ('layer_type', models.IntegerField(choices=[(0, 'Raster'), (1, 'Vector'), (-1, 'Undefined')])),
                ('size', models.IntegerField(blank=True, default=0, null=True)),
                ('is_final_output', models.BooleanField(default=False)),
                ('group', models.CharField(blank=True, max_length=256, null=True)),
                ('file', models.FileField(upload_to=cplus_api.models.layer.output_layer_dir_path)),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_layers', to='cplus_api.scenariotask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('created_on', models.DateTimeField()),
                ('layer_type', models.IntegerField(choices=[(0, 'Raster'), (1, 'Vector'), (-1, 'Undefined')])),
                ('size', models.IntegerField(blank=True, default=0, null=True)),
                ('file', models.FileField(storage=cplus_api.models.layer.select_input_layer_storage, upload_to=cplus_api.models.layer.input_layer_dir_path)),
                ('component_type', models.CharField(choices=[('ncs_pathway', 'ncs_pathway'), ('ncs_carbon', 'ncs_carbon'), ('priority_layer', 'priority_layer')], max_length=255)),
                ('privacy_type', models.CharField(choices=[('private', 'private'), ('internal', 'internal'), ('common', 'common')], default='private', max_length=255)),
                ('last_used_on', models.DateTimeField(blank=True, null=True)),
                ('client_id', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
