# Generated by Django 4.2.7 on 2024-04-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cplus_api', '0002_outputlayer_inputlayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputlayer',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
