# Generated by Django 4.2.7 on 2024-04-09 01:34

from django import apps
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from cplus_api.models.profile import UserRoleType

def add_roles(apps, schema_editor):
    UserRoleType = apps.get_model('cplus_api', 'UserRoleType')
    UserRoleType.objects.create(
        name='Internal',
        description='User who needs persistent data (e.g. the members of CI team)'
    )
    UserRoleType.objects.create(
        name='External',
        description='Normal user that their data can be removed regularly'
    )


def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cplus_api', '0002_outputlayer_inputlayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'User role',
                'verbose_name_plural': 'User roles',
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_profile', to='cplus_api.userroletype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(add_roles, reverse_func)
    ]
