# Generated by Django 4.2.7 on 2024-05-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cplus_api', '0003_userroletype_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputlayer',
            name='component_type',
            field=models.CharField(choices=[('ncs_pathway', 'ncs_pathway'), ('ncs_carbon', 'ncs_carbon'), ('priority_layer', 'priority_layer'), ('reference_layer', 'reference_layer')], max_length=255),
        ),
    ]
