# Generated by Django 4.2.7 on 2024-05-08 01:53

import cplus_api.models.layer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cplus_api', '0004_alter_inputlayer_component_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputlayer',
            name='output_meta',
            field=models.JSONField(blank=True, default=cplus_api.models.layer.default_output_meta, help_text='Output Metadata.'),
        ),
        migrations.AddField(
            model_name='scenariotask',
            name='updated_detail',
            field=models.JSONField(default=dict),
        ),
    ]
