# Generated by Django 4.2.7 on 2024-05-02 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cplus_api', '0004_alter_inputlayer_component_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipartUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(max_length=512)),
                ('input_layer_uuid', models.UUIDField()),
                ('created_on', models.DateTimeField()),
                ('parts', models.IntegerField()),
                ('is_aborted', models.BooleanField(default=False)),
                ('aborted_on', models.DateTimeField(blank=True, null=True)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
