# Generated by Django 4.2.7 on 2024-05-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cplus_api', '0005_multipartupload'),
        ('cplus_api', '0005_outputlayer_output_meta_scenariotask_updated_detail'),
    ]

    operations = [
    ]
