# Generated by Django 4.2.7 on 2024-06-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cplus_api', '0007_alter_inputlayer_component_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariotask',
            name='code_version',
            field=models.TextField(blank=True, default=''),
        ),
    ]
