# Generated by Django 4.2.7 on 2025-04-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cplus_api', '0015_temporarylayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputlayer',
            name='size',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='outputlayer',
            name='size',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
