# Generated by Django 4.2.7 on 2025-04-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cplus_api', '0016_alter_inputlayer_size_alter_outputlayer_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarylayer',
            name='size',
            field=models.BigIntegerField(),
        ),
    ]
