# Generated by Django 4.2.7 on 2025-05-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cplus_api', '0017_alter_temporarylayer_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputlayer',
            name='license',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inputlayer',
            name='version',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
