# Generated by Django 4.2.7 on 2025-05-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cplus_api', '0018_inputlayer_license_inputlayer_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputlayer',
            name='license',
            field=models.TextField(blank=True, null=True),
        ),
    ]
