# Generated by Django 4.2.7 on 2025-12-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cplus_api', '0020_zonalstatisticstask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputlayer',
            name='component_type',
            field=models.CharField(choices=[('ncs_pathway', 'ncs_pathway'), ('ncs_carbon', 'ncs_carbon'), ('priority_layer', 'priority_layer'), ('snap_layer', 'snap_layer'), ('sieve_mask_layer', 'sieve_mask_layer'), ('mask_layer', 'mask_layer'), ('reference_layer', 'reference_layer'), ('stored_carbon', 'stored_carbon')], max_length=255),
        ),
    ]
