# Generated by Django 4.2.7 on 2025-12-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cplus_api', '0021_alter_inputlayer_component_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputlayer',
            name='action',
            field=models.IntegerField(choices=[(0, 'Protect'), (1, 'Restore'), (2, 'Manage'), (-1, 'Undefined')], default=-1),
        ),
    ]
