# Generated by Django 4.2.7 on 2024-04-17 02:44

from django.db import migrations


def add_minio_site(apps, schema_editor):
    """Init minio site record."""
    Site = apps.get_model('sites', 'Site')
    minio_site = Site.objects.filter(
        name__icontains='minio api'
    ).first()
    if not minio_site:
        Site.objects.create(
            domain='api.minio.local:8888',
            name='CPLUS Minio API'
        )


def reverse_add_minio_site(apps, schema_editor):
    """Reverse func"""
    Site = apps.get_model('sites', 'Site')
    minio_site = Site.objects.filter(
        name__icontains='minio api'
    ).first()
    if minio_site:
        minio_site.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('core', '0002_tasklog'),
    ]

    operations = [
        migrations.RunPython(add_minio_site, reverse_add_minio_site),
    ]
