# Generated by Django 4.2.7 on 2024-04-30 03:23

import core.models.preferences
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_init_mino_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='output_group_to_keep',
            field=models.JSONField(blank=True, default=core.models.preferences.default_output_group_to_keep, help_text='Output group to keep from automatic removal.'),
        ),
    ]
