# Generated by Django 4.2.7 on 2024-05-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitepreferences_output_group_to_keep'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='task_runtime_threshold',
            field=models.PositiveIntegerField(default=120, help_text="Max minutes to pass before a task is marked 'Stopped with error'"),
        ),
    ]
