# Generated by Django 4.2.7 on 2024-05-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitepreferences_output_group_to_keep'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='layer_days_to_keep',
            field=models.IntegerField(default=14, help_text='Keep input/output layers until X days.'),
        ),
    ]