# Generated by Django 4.2.7 on 2024-06-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitepreferences_layer_days_to_keep'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='task_runtime_threshold',
            field=models.PositiveIntegerField(default=120, help_text="Max minutes to pass before a task is marked 'Stopped with error'"),
        ),
    ]
